### ISSUE TITLE
The choice of color for constructors is poor in the dark mode

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#106]
They are too dark, badly visible. In the dark mode, all fonts should always have light colors, so one can easily see them.
<img width="412" alt="image" src="https://github.com/anoma/vscode-juvix/assets/62751/89fa1fdc-22bb-49a1-b400-2a0a1a5164bf">

**Comment by jonaprieto** [comment]
Agreed. ChrisHolt created a color palette for us, but it's difficult to read. Let's look for another option to this color.

**Comment by lukaszcz** [comment]
This has been fixed in 0.1.48
