### ISSUE TITLE
Check and install VampIR binaries 

### ISSUE THREAD

**Issue by jonaprieto** [anoma/vscode-juvix#113]
Just like we provide the option to install Juvix from the VSCode extension, we should also offer the possibility to install VampIR in the same way. To achieve this, we can probably modify the lines in installer.ts and use the one-installer from here: https://github.com/jpillora/installer

**Comment by jonaprieto** [comment]
Let's use the `--install-vamp-ir` flag once it's merged

- https://github.com/anoma/juvix-installer/pull/2

**Comment by vrom911** [comment]
Done in #117  through the new VampIR installer script, not the command option
