### ISSUE TITLE
Error with typechecking on change

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#138]
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/807786bd-8ee0-4dc7-9450-c612fabf8f61">

**Comment by jonaprieto** [comment]
@lukaszcz Are you still experimenting this issue after

- #140

**Comment by lukaszcz** [comment]
No, this particular error is gone and typecheck-on-change works mostly fine, though the results are sometimes strange, e.g., error highlighting not disappearing after successful typecheck.
