### ISSUE TITLE
Shift+Alt+R doesn't work for me

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#42]
It's a no-op. It doesn't launch the REPL, even though there are no conflicting keybindings. I think there is some conflict with Alt+R which launches some VSCode popup about searching for regular expressions.

I propose we try changing this to Shift+Alt+E (for Evaluation).

**Comment by lukaszcz** [comment]
This in fact might not be related to Alt+R being used by VSCode, but just a bug in the extension. Whatever shortcut I assign to the command, it doesn't work. It works only by clicking the button.

**Comment by jonaprieto** [comment]
@lukaszcz Does it work if you assign the command loadFileRepl to Shift+Alt+E? I tried, and it didn't work for me. I will leave it without keybinding until we find a better keybinding candidate that works for all.

**Comment by lukaszcz** [comment]
> @lukaszcz Does it work if you assign the command loadFileRepl to Shift+Alt+E? I tried, and it didn't work for me. I will leave it without keybinding until we find a better keybinding candidate that works for all.

As I wrote in the second comment, it doesn't work regardless of what keybinding I assign to loadFileRepl. Very strange. There seems to be something wrong with (assigning keybindings to) this command specifically.
