### ISSUE TITLE
Formating  for JuvixCore and JuvixGeb 

### ISSUE THREAD

**Issue by jonaprieto** [anoma/vscode-juvix#43]
Use the subcommand `read` for each language, respectively.

**Comment by lukaszcz** [comment]
This won't work for JuvixCore, and it's questionable if it's worth the effort to implement proper formatters for JuvixCore and JuvixGeb.

**Comment by jonaprieto** [comment]
Tested Geb formatter with 0.1.39 version, works fine. No formatter for Core, but that's okay. Closing the issue as it appears resolved. Reopen if needed.
