### ISSUE TITLE
The `type` keyword is not highlighted in JuvixCore

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#46]

**Comment by vrom911** [comment]
I have trouble in compiling the code provided in the above picture. Is that valid syntax? I should have something additional done to make it work for me?

**Comment by lukaszcz** [comment]
This is JuvixCore code (our internal Core language), not Juvix syntax. You put JuvixCore code in *.jvc files, which the VSCode extension recognises.
