### ISSUE TITLE
The REPL fails to launch if bash has a different path than the hardcoded one

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#47]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/62751/221917384-aea06e52-2531-4e53-a59f-c6a3f93d08ea.png">

On my Mac system, for example, bash is in `/bin`.

**Comment by jonaprieto** [comment]
There's an option on the Juvix settings to setup the Juvix binary path.

**Comment by lukaszcz** [comment]
> There's an option on the Juvix settings to setup the Juvix binary path.

How does this help? It's the path of `bash` that's the problem, not of Juvix. Btw., `juvix` is in `~/.local/bin` and it is found by the plugin when I click "compile".

**Comment by jonaprieto** [comment]
True, I'll look into this. ;)
