### ISSUE TITLE
Geb files cannot be saved

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#51]
Trying to save a *.geb file reverts to the previous content.

More precisely, I have a file with "6" in it on a single line, try to change it to "32", save, and it reverts back to "6".

**Comment by lukaszcz** [comment]
Maybe this has something to do with autoformatting?

**Comment by jonaprieto** [comment]
> Maybe this has something to do with autoformatting?

I believe so, we had a similar issue some time ago. Can you check if you have the auto formatting option on?

**Comment by lukaszcz** [comment]
I do have it turned on, and it's probably it. When I do formatting manually
with Shift+Option+F it also restores the old content of the file.

**Comment by jonaprieto** [comment]
> More precisely, I have a file with "6" in it on a single line, try to change it to "32", save, and it reverts back to "6".

I cannot reproduce this issue in v0.1.39. Please open it again if you still experience this.
