### ISSUE TITLE
Clicking `run` doesn't work when `.juvix-build` doesn't exist

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#54]
After clicking `run` in a Juvix file I get:
```
The terminal process failed to launch: Starting directory (cwd) "/Users/heliax/Documents/juvix-2/.juvix-build" does not exist.
```

**Comment by lukaszcz** [comment]
That's also one of the (majority of) files for which highlighting doesn't work (#41).

**Comment by jonaprieto** [comment]
- https://github.com/anoma/vscode-juvix/blob/551427f3888980996c575d04125e78bcb89e9cb6/src/config.ts#L68
