### ISSUE TITLE
Formatting doesn't work

### ISSUE THREAD

**Issue by lukaszcz** [anoma/vscode-juvix#98]
When trying to format a file I always get
<img width="464" alt="image" src="https://github.com/anoma/vscode-juvix/assets/62751/59a28844-74f5-477d-8a20-bc4742ab07c2">
except when the file is already formatted - then the entire contents of the file gets deleted!

**Comment by jonaprieto** [comment]
Got the same behaviour.

**Comment by jonaprieto** [comment]
This issue is after changing `juvix dev scope` by `juvix format` in the formatter provider.
